# config/packages/knp_paginator.yaml
knp_paginator:
    page_range: 3                      # Nombre de pages affichées dans la pagination
    default_options:
        page_name: page                 # Nom du paramètre pour la page courante
        sort_field_name: sort           # Nom du paramètre pour le tri
        sort_direction_name: direction  # Nom du paramètre pour la direction du tri
        distinct: true                  # Utilisation de DISTINCT dans les requêtes
    template:
        pagination: '@KnpPaginator/Pagination/bootstrap_v5_pagination.html.twig'  # Template pour Bootstrap 5
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig'

