security:
    # Password hashers
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
            algorithm: auto
            cost: 12  # Strong security
            time_cost: 3
            memory_cost: 128000

    # User provider
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email  # Users authenticate via email

    firewalls:
        # Dev firewall (unchanged)
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        # Main authentication firewall

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\LoginFormAuthAuthenticator
            entry_point: App\Security\LoginFormAuthAuthenticator  # Explicitly set entry point


            logout:
                path: app_logout
                target: app_front_office  # Redirect to FrontOffice after logout
                invalidate_session: true  # Ensure session is fully invalidated

            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800  # 7 days
                path: /

    # Access control rules
    access_control:
        # Public routes
        - { path: ^/login$, roles: PUBLIC_ACCESS }
        - { path: ^/register$, roles: PUBLIC_ACCESS }

        # Logout should only be accessible by authenticated users
        - { path: ^/logout$, roles: IS_AUTHENTICATED_FULLY }

        # FrontOffice routes (User and Admin)
        - { path: ^/profile, roles: [ROLE_USER, ROLE_ADMIN] }
        - { path: ^/front-office, roles: [ROLE_USER, ROLE_ADMIN] }

        # Admin-only routes
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/admin/users, roles: ROLE_ADMIN }  # Admins manage users here
        
        # Regular users can only access their own user profile (adjust in controllers)
        - { path: ^/user, roles: ROLE_USER }
        
        # Default public access
        - { path: ^/, roles: PUBLIC_ACCESS }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10